#28/05/2019 14:07:09| System.Data.SqlClient.SqlException|    em System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   em System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   em System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.Open()
   em Globais.Dao.Base.ExecCommands.RetornaDatareader(String Procedure, List`1 Parameters, String connection) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\Base\ExecCommands.cs:linha 44
   em Globais.Dao.Base.BaseDados.RetornaDataReader(String proc, String sqlTipo, Object obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\Base\BaseDados.cs:linha 40| .Net SqlClient Data Provider| Erro de rede ou específico à instância ao estabelecer conexão com o SQL Server. O servidor não foi encontrado ou não estava acessível. Verifique se o nome da instância está correto e se o SQL Server está configurado para permitir conexões remotas. (provider: Named Pipes Provider, error: 40 - Não foi possível abrir uma conexão com o SQL Server)| Portal
#28/05/2019 15:23:39| System.Data.SqlClient.SqlException|    em System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   em System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   em System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.Open()
   em Globais.Dao.Base.ExecCommands.RetornaDatareader(String Procedure, List`1 Parameters, String connection)
   em Globais.Dao.Base.BaseDados.RetornaDataReader(String proc, String sqlTipo, Object obj)| .Net SqlClient Data Provider| Tempo Limite de Conexão Expirado. O tempo limite decorrido durante a tentativa de consumo da confirmação de handshake pré-logon. Isso ocorre porque houve falha no handshake pré-logon ou o servidor não pôde responder a tempo.  A duração da tentativa de conexão com este servidor foi: [Pre-Login] initialization=15720; handshake=0; | Portal
#28/05/2019 16:43:45| System.Data.SqlClient.SqlException|    em System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   em System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   em System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.Open()
   em Globais.Dao.Base.ExecCommands.RetornaDatareader(String Procedure, List`1 Parameters, String connection) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\Base\ExecCommands.cs:linha 44
   em Globais.Dao.Base.BaseDados.RetornaDataReader(String proc, String sqlTipo, Object obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\Base\BaseDados.cs:linha 40| .Net SqlClient Data Provider| Erro de rede ou específico à instância ao estabelecer conexão com o SQL Server. O servidor não foi encontrado ou não estava acessível. Verifique se o nome da instância está correto e se o SQL Server está configurado para permitir conexões remotas. (provider: Named Pipes Provider, error: 40 - Não foi possível abrir uma conexão com o SQL Server)| Portal
#28/05/2019 16:44:46| System.Data.SqlClient.SqlException|    em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.Open()
   em Globais.Dao.Base.ExecCommands.RetornaDatareader(String Procedure, List`1 Parameters, String connection) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\Base\ExecCommands.cs:linha 44
   em Globais.Dao.Base.BaseDados.RetornaDataReader(String proc, String sqlTipo, Object obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\Base\BaseDados.cs:linha 40| .Net SqlClient Data Provider| Erro de rede ou específico à instância ao estabelecer conexão com o SQL Server. O servidor não foi encontrado ou não estava acessível. Verifique se o nome da instância está correto e se o SQL Server está configurado para permitir conexões remotas. (provider: Named Pipes Provider, error: 40 - Não foi possível abrir uma conexão com o SQL Server)| Portal
#28/05/2019 16:44:48| System.Data.SqlClient.SqlException|    em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.Open()
   em Globais.Dao.Base.ExecCommands.RetornaDatareader(String Procedure, List`1 Parameters, String connection) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\Base\ExecCommands.cs:linha 44
   em Globais.Dao.Base.BaseDados.RetornaDataReader(String proc, String sqlTipo, Object obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\Base\BaseDados.cs:linha 40| .Net SqlClient Data Provider| Erro de rede ou específico à instância ao estabelecer conexão com o SQL Server. O servidor não foi encontrado ou não estava acessível. Verifique se o nome da instância está correto e se o SQL Server está configurado para permitir conexões remotas. (provider: Named Pipes Provider, error: 40 - Não foi possível abrir uma conexão com o SQL Server)| Portal
#28/05/2019 16:44:48| System.NullReferenceException|    em Globais.Dao.GlobaisUsuarioDao.LoginUsuario(GlobaisUsuarioBE obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\GlobaisUsuarioDao.cs:linha 22
   em Globais.BLL.GlobaisUsuarioBLL.Login(GlobaisUsuarioBE obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.BLL\GlobaisUsuarioBLL.cs:linha 13
   em Portal.Controllers.LoginController.Index(String txtLogin, String txtSenha, String cbolembrarsenha) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\Portal\Controllers\LoginController.cs:linha 82| Globais.Dao| Referência de objeto não definida para uma instância de um objeto.| Portal
#28/05/2019 16:44:48| System.NullReferenceException|    em Globais.Dao.GlobaisUsuarioDao.LoginUsuario(GlobaisUsuarioBE obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\GlobaisUsuarioDao.cs:linha 22
   em Globais.BLL.GlobaisUsuarioBLL.Login(GlobaisUsuarioBE obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.BLL\GlobaisUsuarioBLL.cs:linha 13
   em Portal.Controllers.LoginController.Index(String txtLogin, String txtSenha, String cbolembrarsenha) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\Portal\Controllers\LoginController.cs:linha 82| Globais.Dao| Referência de objeto não definida para uma instância de um objeto.| Portal
#28/05/2019 16:44:48| System.NullReferenceException|    em Globais.Dao.GlobaisUsuarioDao.LoginUsuario(GlobaisUsuarioBE obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\GlobaisUsuarioDao.cs:linha 22
   em Globais.BLL.GlobaisUsuarioBLL.Login(GlobaisUsuarioBE obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.BLL\GlobaisUsuarioBLL.cs:linha 13
   em Portal.Controllers.LoginController.Index(String txtLogin, String txtSenha, String cbolembrarsenha) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\Portal\Controllers\LoginController.cs:linha 82| Globais.Dao| Referência de objeto não definida para uma instância de um objeto.| Portal
#28/05/2019 16:45:11| System.Data.SqlClient.SqlException|    em System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   em System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   em System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.Open()
   em Globais.Dao.Base.ExecCommands.RetornaDatareader(String Procedure, List`1 Parameters, String connection) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\Base\ExecCommands.cs:linha 44
   em Globais.Dao.Base.BaseDados.RetornaDataReader(String proc, String sqlTipo, Object obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\Base\BaseDados.cs:linha 40| .Net SqlClient Data Provider| Erro de rede ou específico à instância ao estabelecer conexão com o SQL Server. O servidor não foi encontrado ou não estava acessível. Verifique se o nome da instância está correto e se o SQL Server está configurado para permitir conexões remotas. (provider: Named Pipes Provider, error: 40 - Não foi possível abrir uma conexão com o SQL Server)| Portal
#28/05/2019 16:45:11| System.NullReferenceException|    em Globais.Dao.GlobaisUsuarioDao.LoginUsuario(GlobaisUsuarioBE obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.Dao\GlobaisUsuarioDao.cs:linha 22
   em Globais.BLL.GlobaisUsuarioBLL.Login(GlobaisUsuarioBE obj) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\ProjectsGlobais\Globais.BLL\GlobaisUsuarioBLL.cs:linha 13
   em Portal.Controllers.LoginController.Index(String txtLogin, String txtSenha, String cbolembrarsenha) na E:\MeusDocumentos\Pessoal\__Dados\GwmNet_Faturamento\Portal\Controllers\LoginController.cs:linha 82| Globais.Dao| Referência de objeto não definida para uma instância de um objeto.| Portal
